name: resume
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  cloud_firestore: ^5.6.8
  dio: ^5.8.0+1
  firebase_core: ^3.13.0
  firebase_storage: ^12.4.6
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_hooks: ^0.21.2
  flutter_svg: ^2.1.0
  freezed_annotation: ^3.0.0
  gap: ^3.0.1
  go_router: ^15.1.2
  hooks_riverpod: ^2.6.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  responsive_framework: ^1.5.1
  retrofit: ^4.4.2
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  riverpod_generator: ^2.6.5
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  retrofit_generator: ">=8.0.0 <10.0.0" # for Dart 3.3 use ^9.0.0

flutter:
  uses-material-design: true

  assets:
    # - .env
    - assets/
    - assets/images/
    - assets/icons/
    - assets/icons/tech_stack/

  fonts:
    - family: "Pretendard"
      fonts:
        - asset: assets/fonts/Pretendard-Thin.ttf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.ttf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.ttf
          weight: 800

flutter_assets:
  assets_path: assets/
  output_path: lib/core/constants/
  filename: assets.dart
  ignore_comments: true
