// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1s3V7iNOnFIr1XeOmP0NUiwqyyEzmsv0',
    appId: '1:270634291004:web:6a03292f591e5293479839',
    messagingSenderId: '270634291004',
    projectId: 'instagram-resume',
    authDomain: 'instagram-resume.firebaseapp.com',
    storageBucket: 'instagram-resume.firebasestorage.app',
    measurementId: 'G-KHBWP5ZJ2F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEPnyHlvHMENRG3qil-UEtkNER5-XBbDU',
    appId: '1:270634291004:android:1d2f84a1a72b3d41479839',
    messagingSenderId: '270634291004',
    projectId: 'instagram-resume',
    storageBucket: 'instagram-resume.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt-URqVCQaPldtwrHIzA5tTaikAmwnti8',
    appId: '1:270634291004:ios:43d7281922780d7b479839',
    messagingSenderId: '270634291004',
    projectId: 'instagram-resume',
    storageBucket: 'instagram-resume.firebasestorage.app',
    iosBundleId: 'com.example.resume',
  );

}